### ISSUE TITLE
feat: Dropdown

### ISSUE THREAD

**Issue by grazioti** [mundorum-lab/datasci#71]
Implement dynamic rendering of input of type DropDown in a component's configuration modal.

The input view must accept the following parameter:
~~~
options: [{"name":<string>, "value":<string>}]
~~~

where each list item is one of the DropDown menu options, containing name and value.

**Comment by Jonhyog** [comment]
One should be able to define a default option using the selected atribute. So the input view should accept the following:

`options: [{"name":<string>, "value":<string>, "selected":<boolean>}]`

Is important to note that only one of the options can have "selected: true".
