### ISSUE TITLE
feat: Component that clears the database

### ISSUE THREAD

**Issue by FelipeMatoba** [mundorum-lab/datasci#86]
Having a component that clears the database would be useful so that it's not necessary to clear the browser cache.

**Comment by JoaoGuilhermeAlvesSantos** [comment]
Thanks for your awareness Felipe,

This seems useful to our project. I added this to the Data Group's commitment, and I'll develop it as soon as possible.

**Comment by JoaoGuilhermeAlvesSantos** [comment]
Good morning, I have completed the development of the new feature that was requested, and it is already working in the branch mentioned in the Issue. I will soon finish the documentation and submit it to the main branch

**Comment by JoaoGuilhermeAlvesSantos** [comment]
Issue resolved by Merge Request #122 

This issue will be closed
